name: "Build and Push to Server"
on:
  pull_request:
    types:
      - closed

env:
  working-directroy: ./DEPLOY

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@master

      - name: Push Dockerfile to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: DEPLOY/Dockerfile
          target: /home/ubuntu/

      - name: Build and Push Dockerfile from server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu
            sudo docker build -t elliotdragon/insurance-app .
            sudo docker push elliotdragon/insurance-app

      - name: Stop and delete Container on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo docker kill insurance
            sudo docker rm -f insurance
            sudo docker rmi -f elliotdragon/insurance-app:latest

      - name: Pull and start new Docker Container on Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo docker pull elliotdragon/insurance-app:latest
            sudo docker run --name insurance -d -p 3000:3000 elliotdragon/insurance-app:latest
